# MCKOOK
# wiki 地址: https://github.com/meteorOSS/McKook

setting:
  # 黑名单世界 (在该世界的玩家消息不会被转发)
  black-worlds:
    - 'exam'
  # 使用频道号
  guild: '53641007'
  channel:
    闲聊频道: '5697409055338359'
    公告频道: '1252730549716403'
    白名单申请: '6683142884528255'

kook:
  bot-token: '填机器人token'